#!/usr/bin/env python3
"""build_attendance_sheet.py — attendance matrix, %-attendance, and absence alerts.

Computes an attendance matrix and per-student summary from one or more
per-section class-attendance JSON ledgers, refreshes each JSON's ``summary``
block in place, emits a per-section CSV (for a Google Sheets import), and
prints a readable alerts/flags report to stdout.

Stdlib only. No network access. Fully deterministic.

CLI
---
    python3 build_attendance_sheet.py <attendance-Ad.json> [<attendance-Mk.json> ...] \\
        [--csv-dir <dir>] [--no-write]

    --csv-dir DIR   Directory to write the per-section CSV(s) into.
                    Defaults to the directory of each input JSON file.
    --no-write      Compute + write CSV + print report, but do NOT modify the
                    input JSON files (skip the summary write-back).

Input JSON schema (per section file), abbreviated
--------------------------------------------------
    {
      "section": {"id": "Ad", "label": "Administración"},
      "policy": {"class_present_threshold": 0.5, "max_absences": 8,
                 "absence_alert_fraction": 0.75},
      "miro_account_map": {},
      "roster": [
        {"carne": "24001301", "name": "...", "email": "...",
         "status": "active" | "dropped", "joined_session": "S01", "notes": ""}
      ],
      "sessions": {
        "S01": {
          "date": "2026-07-06", "type": "virtual", "mode": "miro",
          "exercises": [...], "boards": {...}, "reviewed_at": "...",
          "records": {
            "24001301": {
              "exercises": {...}, "exercises_participated": 1,
              "exercises_total": 1, "participation_rate": 1.0,
              "present": true, "flags": [], "notes": ""
            }
          },
          "flags": {"new_students": [], "unmatched_frames": [],
                     "shared_account_authors": []}
        }
        // manual-mode sessions instead have records[carne] =
        //   {"present": bool, "source": "acta ...", "notes": ""}
      },
      "summary": {}   // regenerated by this script
    }

``sessions`` may be an empty object — every student then shows 0% attendance
and no session columns/alerts are produced.

Outputs
-------
1. Refreshed ``summary`` block written back into each input JSON (unless
   ``--no-write``), containing: echoed policy, alert_threshold_absences,
   sessions_recorded, per_student stats, alerts, new_students, flag_queue.
2. ``<csv-dir>/<section.id>-asistencia.csv`` — one row per roster student,
   with a column per session (glyphs "✓ / ✗ / –"), plus
   % Asistencia / Ausencias / Alerta columns.
3. A human-readable report on stdout: legend, per-section header, absence
   alerts, newly detected students, and the flag review queue.
"""

import argparse
import csv
import json
import math
import os
import sys

EN_DASH = "–"
CHECK = "✓"
CROSS = "✗"
WARN = "⚠"


def session_num(key):
    """Return the integer session number for a key like 'S01' -> 1."""
    return int(key[1:])


def sorted_session_keys(sessions):
    """Sessions dict keys sorted ascending by their numeric part."""
    return sorted(sessions.keys(), key=session_num)


def compute_cell(session_key, student, sessions):
    """Return (glyph, counted, present) for one student/session cell.

    counted is True if the student was enrolled by this session (i.e. this
    session counts toward the denominator). present is True if the student
    has a present==True record for this session (only meaningful when
    counted is True).
    """
    joined = student.get("joined_session") or "S01"
    try:
        joined_num = session_num(joined)
    except (ValueError, IndexError):
        joined_num = 0

    if session_num(session_key) < joined_num:
        return EN_DASH, False, False

    session = sessions.get(session_key) or {}
    records = session.get("records") or {}
    record = records.get(student.get("carne")) or {}
    is_present = record.get("present") is True

    return (CHECK if is_present else CROSS), True, is_present


def compute_section(data):
    """Compute the full attendance matrix + summary for one section's data.

    Returns a dict with keys: session_keys, rows (per-student matrix rows),
    per_student (summary stats), alerts, new_students, flag_queue,
    alert_threshold, policy.
    """
    policy = data.get("policy") or {}
    max_absences = policy.get("max_absences", 8)
    alert_fraction = policy.get("absence_alert_fraction", 0.75)
    alert_threshold = math.ceil(alert_fraction * max_absences)

    roster = data.get("roster") or []
    sessions = data.get("sessions") or {}
    session_keys = sorted_session_keys(sessions)

    rows = []
    per_student = {}

    for student in roster:
        carne = student.get("carne")
        name = student.get("name", "")
        status = student.get("status", "active")

        cells = []
        numerator = 0
        denominator = 0
        for skey in session_keys:
            glyph, counted, present = compute_cell(skey, student, sessions)
            cells.append(glyph)
            if counted:
                denominator += 1
                if present:
                    numerator += 1

        attendance_pct = round(100 * numerator / denominator, 1) if denominator else 0.0
        absences = denominator - numerator
        alert = absences >= alert_threshold

        rows.append({
            "carne": carne,
            "name": name,
            "status": status,
            "cells": cells,
            "attendance_pct": attendance_pct,
            "absences": absences,
            "alert": alert,
        })

        per_student[carne] = {
            "name": name,
            "status": status,
            "present": numerator,
            "absent": absences,
            "applicable_sessions": denominator,
            "attendance_pct": attendance_pct,
            "absences": absences,
            "alert": alert,
        }

    alerts = sorted(
        (
            {"carne": carne, "name": stats["name"], "absences": stats["absences"], "of_max": max_absences}
            for carne, stats in per_student.items()
            if stats["alert"]
        ),
        key=lambda a: a["absences"],
        reverse=True,
    )

    new_students_seen = {}
    new_students_order = []
    for skey in session_keys:
        session = sessions.get(skey) or {}
        flags = session.get("flags") or {}
        for carne in flags.get("new_students") or []:
            if carne not in new_students_seen:
                new_students_seen[carne] = skey
                new_students_order.append(carne)
    new_students = [{"carne": c, "session": new_students_seen[c]} for c in new_students_order]

    flag_queue = []
    for skey in session_keys:
        session = sessions.get(skey) or {}
        records = session.get("records") or {}
        for carne, record in records.items():
            rec_flags = record.get("flags") or []
            if rec_flags:
                flag_queue.append({"carne": carne, "session": skey, "flags": rec_flags})

    return {
        "session_keys": session_keys,
        "rows": rows,
        "per_student": per_student,
        "alerts": alerts,
        "new_students": new_students,
        "flag_queue": flag_queue,
        "alert_threshold": alert_threshold,
        "max_absences": max_absences,
        "policy": policy,
    }


def build_summary(computed):
    """Build the JSON-serializable 'summary' block from computed results."""
    return {
        "policy": computed["policy"],
        "alert_threshold_absences": computed["alert_threshold"],
        "sessions_recorded": computed["session_keys"],
        "per_student": computed["per_student"],
        "alerts": computed["alerts"],
        "new_students": computed["new_students"],
        "flag_queue": computed["flag_queue"],
    }


def write_csv(section_id, computed, csv_dir):
    """Write the per-section CSV file. Returns the path written."""
    os.makedirs(csv_dir, exist_ok=True)
    path = os.path.join(csv_dir, f"{section_id}-asistencia.csv")

    header = ["Carné", "Nombre", "Estado"] + computed["session_keys"] + [
        "% Asistencia", "Ausencias", "Alerta",
    ]

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for row in computed["rows"]:
            writer.writerow(
                [row["carne"], row["name"], row["status"]]
                + row["cells"]
                + [row["attendance_pct"], row["absences"], WARN if row["alert"] else ""]
            )

    return path


def print_report(section_id, section_label, computed):
    """Print the readable per-section report to stdout."""
    n_students = len(computed["rows"])
    n_sessions = len(computed["session_keys"])
    max_absences = computed["max_absences"]
    threshold = computed["alert_threshold"]

    print(f"[{section_id} {section_label}] {n_students} alumnos · {n_sessions} sesiones registradas")

    print(f"⚠ ALERTAS DE AUSENCIAS (≥ {threshold}/{max_absences}):")
    if computed["alerts"]:
        for a in computed["alerts"]:
            print(f"  {a['carne']}  {a['name']}  {a['absences']}/{a['of_max']}")
    else:
        print("  ninguna")

    print("🆕 NUEVOS ALUMNOS DETECTADOS:")
    if computed["new_students"]:
        for ns in computed["new_students"]:
            print(f"  {ns['carne']}  {ns['session']}")
    else:
        print("  ninguno")

    print("🚩 COLA DE REVISIÓN (flags):")
    if computed["flag_queue"]:
        for fq in computed["flag_queue"]:
            print(f"  {fq['carne']}  {fq['session']}  {fq['flags']}")
    else:
        print("  ninguna")

    print()


def process_file(path, csv_dir_arg, no_write):
    """Process a single section JSON file end-to-end."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    section = data.get("section") or {}
    section_id = section.get("id", os.path.splitext(os.path.basename(path))[0])
    section_label = section.get("label", "")

    computed = compute_section(data)

    if not no_write:
        data["summary"] = build_summary(computed)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")

    csv_dir = csv_dir_arg or os.path.dirname(os.path.abspath(path))
    csv_path = write_csv(section_id, computed, csv_dir)

    print_report(section_id, section_label, computed)

    return csv_path


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Build attendance matrix/CSV and refresh summary from class-attendance JSON ledgers.",
    )
    parser.add_argument("json_paths", nargs="+", help="Path(s) to per-section attendance JSON files.")
    parser.add_argument("--csv-dir", default=None, help="Directory to write per-section CSV(s) into.")
    parser.add_argument("--no-write", action="store_true", help="Do not write back the JSON 'summary' block.")
    args = parser.parse_args(argv)

    print("✓ presente · ✗ ausente · – no inscrito aún")
    print()

    for path in args.json_paths:
        process_file(path, args.csv_dir, args.no_write)

    return 0


if __name__ == "__main__":
    sys.exit(main())
